### ISSUE TITLE
transform configuration

### ISSUE THREAD

**Issue by konsumer** [defunctzombie/node-enchilada#22]
Maybe I am doing this wrong, but I can't seem to load presets for babelify.

I tried package.json (which works for `browserify`) like this:

``` json
{
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "es2015",
            "react"
          ]
        }
      ],
      [
        "browserify-css",
        {
          "autoInject": true
        }
      ]
    ]
  }
}
```

and I tried in my server-code, like this:

``` js
app.use(enchilada({
    src: __dirname,
    cache: process.env.NODE_ENV === 'production',
    compress: process.env.NODE_ENV === 'production', 
    debug: process.env.NODE_ENV !== 'production',
    routes: {
      '/bundle.js': __dirname + '/index.js'
    },
    transforms: [
      [babelify, {"presets": ["es2015","react"]}],
      css
    ]
}))
```

I also tried, like this:

``` js
app.use(enchilada({
    src: __dirname,
    cache: process.env.NODE_ENV === 'production',
    compress: process.env.NODE_ENV === 'production', 
    debug: process.env.NODE_ENV !== 'production',
    routes: {
      '/bundle.js': __dirname + '/index.js'
    },
    transforms: [
      babelify,
      css
    ]
}))
```

**Comment by defunctzombie** [comment]
You would need to find a way to pass in a pre-configured transform. There is no way to pass options to a transform like this as far as I am aware and this is the first I see that browserify syntax for passing options to transforms.

One thought would be a transform function that just returns a transform configured the way you need.

**Comment by konsumer** [comment]
Thanks for the reply. I switched to browserify-middleware, which reads what I have in my package.json.

**Comment by defunctzombie** [comment]
Cool! Also recommend webpack and webpack-dev-middleware.
